// TestModeView_TestInfo.h : 선언 파일입니다.
//

#if !defined(ZT_TEST_MODE_VIEW_INFO_INCLUDED_)
#define ZT_TEST_MODE_VIEW_INFO_INCLUDED_

enum
{
	SAVE_TEST_INI_DOWNLOAD_FIXED_POSITION = 0,
	SAVE_TEST_INI_LOG_SAVE_FIXED_POSITION,

	SAVE_TEST_INI_MAX
};


//---------------------------------------------------------------------------------
// SPEC INI FILE NAME

#define DND_MAX_SPEC_INI								"05_DND_MAX_SPEC.INI"
#define DND_MIN_SPEC_INI								"05_DND_MIN_SPEC.INI"
#define DND_H_GAP_SPEC_INI								"06_DND_H_GAP_SPEC.INI"
#define DND_V_GAP_SPEC_INI								"06_DND_V_GAP_SPEC.INI"

#define HF_DND_MIN_SPEC_INI								"07_HF_DND_MIN_SPEC.INI"
#define HF_DND_MAX_SPEC_INI								"07_HF_DND_MAX_SPEC.INI"
#define HF_DND_H_GAP_SPEC_INI							"08_HF_DND_H_GAP_SPEC.INI"
#define HF_DND_V_GAP_SPEC_INI							"08_HF_DND_V_GAP_SPEC.INI"

#define ONLY_SELF_DND_TX_MAX_SPEC_INI					"21_ONLY_SELF_DND_TX_MAX_SPEC.INI"
#define ONLY_SELF_DND_TX_MIN_SPEC_INI					"21_ONLY_SELF_DND_TX_MIN_SPEC.INI"
#define ONLY_SELF_DND_RX_MAX_SPEC_INI					"21_ONLY_SELF_DND_RX_MAX_SPEC.INI"
#define ONLY_SELF_DND_RX_MIN_SPEC_INI					"21_ONLY_SELF_DND_RX_MIN_SPEC.INI"

#define SELF_DND_TX_MIN_SPEC_INI						"09_SELF_DND_TX_MIN_SPEC.INI"
#define SELF_DND_TX_MAX_SPEC_INI						"09_SELF_DND_TX_MAX_SPEC.INI"
#define SELF_DND_TX_H_GAP_SPEC_INI						"10_SELF_DND_TX_H_GAP_SPEC.INI"

#define SELF_DND_RX_MIN_SPEC_INI						"09_SELF_DND_RX_MIN_SPEC.INI"
#define SELF_DND_RX_MAX_SPEC_INI						"09_SELF_DND_RX_MAX_SPEC.INI"
#define SELF_DND_RX_H_GAP_SPEC_INI						"10_SELF_DND_RX_H_GAP_SPEC.INI"

#define SELF_SATURATION_TX_MIN_SPEC_INI					"11_SELF_SATURATION_TX_MIN_SPEC.INI"
#define SELF_SATURATION_TX_MAX_SPEC_INI					"11_SELF_SATURATION_TX_MAX_SPEC.INI"

#define SELF_SATURATION_RX_MIN_SPEC_INI					"11_SELF_SATURATION_RX_MIN_SPEC.INI"
#define SELF_SATURATION_RX_MAX_SPEC_INI					"11_SELF_SATURATION_RX_MAX_SPEC.INI"

#define MEASURE_DELTA_MIN_SPEC_INI						"16_MEASURE_DELTA_MIN_SPEC.INI"
#define MEASURE_DELTA_MAX_SPEC_INI						"16_MEASURE_DELTA_MAX_SPEC.INI"

#define MEASURE_DELTA_SELF_RX_MIN_SPEC_INI				"16_MEASURE_DELTA_SELF_RX_MIN_SPEC.INI"
#define MEASURE_DELTA_SELF_RX_MAX_SPEC_INI				"16_MEASURE_DELTA_SELF_RX_MAX_SPEC.INI"
#define MEASURE_DELTA_SELF_TX_MIN_SPEC_INI				"16_MEASURE_DELTA_SELF_TX_MIN_SPEC.INI"
#define MEASURE_DELTA_SELF_TX_MAX_SPEC_INI				"16_MEASURE_DELTA_SELF_TX_MAX_SPEC.INI"

#define DIGITAL_WHEEL_MAX_SPEC_INI						"17_DIGITAL_WHEEL_MAX_SPEC.INI"
#define DIGITAL_WHEEL_MIN_SPEC_INI						"17_DIGITAL_WHEEL_MIN_SPEC.INI"

#define CND_MAX_SPEC_INI								"23_CND_MAX_SPEC.INI"
#define CND_MIN_SPEC_INI								"23_CND_MIN_SPEC.INI"
//---------------------------------------------------------------------------------
// TEST_CONF.INI

#define TEST_CONF_INI									"TEST_CONF.INI"



// CATEGORY
#define INI_CATEGORY_TSM_TEST							"TSM TEST"
#define INI_CATEGORY_DEFAULT							"DEFAULT"
#define INI_CATEGORY_LOG								"LOG"
#define INI_CATEGORY_PASSWORD							"PASSWORD"
#define INI_CATEGORY_INFORMATION						"INFORMATION"
#define INI_CATEGORY_BARCODE							"BARCODE"
#define INI_CATEGORY_FW_DOWNLOAD						"FW DOWNLOAD"
#define INI_CATEGORY_CHECK_PIN							"CHECK PIN"
#define INI_CATEGORY_CHECK_VERSION						"CHECK VERSION"
#define INI_CATEGORY_DND								"DND"
#define INI_CATEGORY_HF_DND								"HF DND"
#define INI_CATEGORY_HIGH_VOLTAGE						"HIGH VOLTAGE"
#define INI_CATEGORY_ONLYSELF_DND						"ONLY SELF DND"
#define INI_CATEGORY_SELF_DND							"SELF DND"
#define INI_CATEGORY_SFR_DATA							"SFR DATA"
#define INI_CATEGORY_SELF_SATURATION					"SELF SATURATION"
#define INI_CATEGORY_TRX_SHORT							"TRX SHORT"
#define INI_CATEGORY_CURRENT_CONSUMPTION				"CURRENT CONSUMPTION"
#define INI_CATEGORY_MEASURE_DELTA						"MEASURE DELTA"
#define INI_CATEGORY_HW_CALIBRATION						"HW CALIBRATION"
#define INI_CATEGORY_JITTER								"JITTER"
#define INI_CATEGORY_DIGITAL_WHEEL						"DIGITAL_WHEEL"
#define INI_CATEGORY_ADD_TEST_ITEM						"ADD TEST ITEM"
#define INI_CATEGORY_CHECK_NOISE						"NOISE"
#define INI_CATEGORY_CND								"CND"					//add 2022.11.14 for ZTM730 CND
#define INI_CATEGORY_I2C_CHECK						"I2C CHECK"
#define INI_CATEGORY_DEV_TOOL							"DEV_TOOL"

// TSM TEST
#define INI_ITEM_TSM_TEST_MPZTD_VERSION					"MPZTD VERSION"


// DEFAULT

#define INI_ITEM_DEFAULT_USE_IFE						"USE IFE"
#define INI_ITEM_DEFAULT_MULTI_DEVICE					"MULTI DEVICE"
#define INI_ITEM_DEFAULT_MULTI_DEVICE_COUNT				"MULTI DEVICE COUNT"
#define INI_ITEM_DEFAULT_START_INDIVIDUAL_TEST			"START INDIVIDUAL TEST"
#define INI_ITEM_DEFAULT_IC_TYPE						"IC TYPE"
#define INI_ITEM_DEFAULT_SLAVE_ADDRESS					"SLAVE ADDRESS"
#define INI_ITEM_DEFAULT_STANDBY_SEC					"STANDBY SEC"
#define INI_ITEM_DEFAULT_HID_MODE						"HID MODE"
#define INI_ITEM_DEFAULT_MODULE_VENDOR					"MODULE VENDOR"
#define INI_ITEM_DEFAULT_USE_RETRY						"USE COUNT"
#define INI_ITEM_DEFAULT_All_RETRY_COUNT				"ALL RETRY COUNT"
#define INI_ITEM_DEFAULT_USE_MPTOOL						"USE MPTOOL VER"
#define INI_ITEM_DEFAULT_MPTOOL_VER_COUNT				"MPTOOL VER CHECK"


// LOG
#define INI_ITEM_LOG_SAVE_RESULT						"SAVE RESULT"
#define INI_ITEM_LOG_SAVE_FIXED_POSITION				"SAVE FIXED POSITION"
#define INI_ITEM_LOG_SAVE_RESULT_PATH					"SAVE RESULT PATH"
#define INI_ITEM_LOG_CREATE_PASS_FAIL_DIR				"CREATE PASS FAIL DIRECOTRY"

// PASSWORD
#define INI_ITEM_PASSWORD_ADMINISTRATOR					"ADMINISTRATOR"
#define INI_ITEM_PASSWORD_USE_STARTUP					"USE STARTUP"
#define INI_ITEM_PASSWORD_STARTUP						"STARTUP"

// INFORMATION
#define INI_ITEM_INFORMATION_CUSTOMER					"CUSTOMER"
#define INI_ITEM_INFORMATION_PROJECT_NAME				"PROJECT NAME"
#define INI_ITEM_INFORMATION_USER_NUMBER				"USER NUMBER"
#define INI_ITEM_INFORMATION_ADDITIONAL_LOG				"ADDITIONAL LOG CONTENT"
#define INI_ITEM_INFORMATION_TEST_NAME					"TEST NAME"
#define INI_ITEM_INFORMATION_TEST_STAGE					"TEST STAGE"
#define INI_ITEM_INFORMATION_MODULE_MAKER				"MODULE MAKER"
#define INI_ITEM_INFORMATION_IQC_OQC					"IQC_OQC"

// BARCODE
#define INI_ITEM_BARCODE_USE_BARCODE					"USE BARCODE"
#define INI_ITEM_BARCODE_Auto_Start_TEST				"Auto Start TEST"
#define INI_ITEM_BARCODE_FIXED_BARCODE_LENGTH			"FIXED BARCODE LENGTH"
#define INI_ITEM_BARCODE_LENGTH							"BARCODE LENGTH"
#define INI_ITEM_BARCODE_DISPLAY_IN_TEST				"BARCODE DISPLAY IN TEST"
#define INI_ITEM_BARCODE_AUTO_RESET_TIME				"BARCODE AUTO RESET TIME"

// FW_DOWNLOAD
#define INI_ITEM_FW_DOWNLOAD_CHECK_DOWNLOAD				"CHECK FW DOWNLOAD"
#define INI_ITEM_FW_DOWNLOAD_FIXED_POSITION				"FIXED POSITION"
#define INI_ITEM_FW_DOWNLOAD_PATH						"PATH"
#define INI_ITEM_FW_DOWNLOAD_RETRY_COUNT				"RETRY COUNT"
#define INI_ITEM_FW_DOWNLOAD_SAVE_INFO					"SAVE INFO"
#define INI_ITEM_FW_DOWNLOAD_SAVE_INFO_LOCATION			"SAVE INFO LOCATION"
#define INI_ITEM_FW_DOWNLOAD_VERIFY_FIRMWARE			"VERIFY FIRMWARE"
#define INI_ITEM_FW_DOWNLOAD_VERIFY_AFTER_DOWNLOAD		"VERIFY AFTER DOWNLOAD"
#define INI_ITEM_FW_DOWNLOAD_BURST_UPGRADE				"BURST UPGRADE"
#define INI_ITEM_FW_DOWNLOAD_BURST_UPGRADE_REAL			"BURST UPGRADE REAL"
#define INI_ITEM_FW_DOWNLOAD_FORCE_UPGRADE				"FORCE UPGRADE"
#define INI_ITEM_FW_DOWNLOAD_EMERGENCY					"EMERGENCY UPGRADE"

#define INI_ITEM_FW_DOWNLOAD_CHANGE_NVM_TIMING			"CHANGE NVM TIMING"

#define INI_ITEM_FW_DOWNLOAD_IUM_FORMAT					"IUM FORMAT"

#define INI_ITEM_FW_DOWNLOAD_CHECK_EEPROM_BIT			"CHECK EEPROM BIT"
#define INI_ITEM_FW_DOWNLOAD_USE_NVM_PGM_VERIFY			"USE NVM PGM VERIFY"

#define INI_ITEM_FW_DOWNLOAD_PROJECT_ID					"PROJECT ID"
#define INI_ITEM_FW_DOWNLOAD_DEVICE_ID					"DEVICE ID"

// CHECK_PIN
#define INI_ITEM_CHECK_PIN_INTERRUPT					"INTERRUPT"
#define INI_ITEM_CHECK_PIN_RESET						"RESET"
#define INI_ITEM_CHECK_PIN_RESET_GPIO					"RESET_GPIO"

// CHECK VERSION
#define INI_ITEM_CHECK_VERSION_CHECK_VERSION			"CHECK_VERSION"
#define INI_ITEM_CHECK_VERSION_CHECK_AUTO_FW_DOWNLOAD	"CHECK_AUTO_FW_DOWNLOAD"
#define INI_ITEM_CHECK_VERSION_IC_REVISION				"IC REVISION"
#define INI_ITEM_CHECK_VERSION_HW_ID					"HW ID"
#define INI_ITEM_CHECK_VERSION_MODULE_ID				"MODULE ID"
#define INI_ITEM_CHECK_VERSION_MAJOR_VERSION			"MAJOR VERSION"
#define INI_ITEM_CHECK_VERSION_MINOR_VERSION			"MINOR VERSION"
#define INI_ITEM_CHECK_VERSION_RELEASE_VERSION			"RELEASE VERSION"

#define INI_ITEM_CHECK_VERSION_IUM						"CHECK_IUM"
// CHECK IUM
#define INI_ITEM_CHECK_I2C								"CHECK I2C"
#define INI_ITEM_CHECK_I2C_LEVEL						"I2C LEVEL"

// CURRENT CONSUMPTION
#define INI_ITEM_CURRENT_CONSUMPTION_CHECK_ACTIVE		"ACTIVE CHECK"
#define INI_ITEM_CURRENT_CONSUMPTION_THR_ACTIVE_MAX		"ACTIVE THR MAX"
#define INI_ITEM_CURRENT_CONSUMPTION_THR_ACTIVE_MIN		"ACTIVE THR MIN"
#define INI_ITEM_CURRENT_CONSUMPTION_AVG_MS_ACTIVE		"ACTIVE AVG MS"

#define INI_ITEM_CURRENT_CONSUMPTION_CHECK_IDLE			"IDLE CHECK"
#define INI_ITEM_CURRENT_CONSUMPTION_THR_IDLE			"IDLE THR"
#define INI_ITEM_CURRENT_CONSUMPTION_AVG_MS_IDLE		"IDLE AVG MS"

#define INI_ITEM_CURRENT_CONSUMPTION_CHECK_SLEEP		"SLEEP CHECK"
#define INI_ITEM_CURRENT_CONSUMPTION_THR_SLEEP			"SLEEP THR"
#define INI_ITEM_CURRENT_CONSUMPTION_AVG_MS_SLEEP		"SLEEP AVG MS"

#define INI_ITEM_CURRENT_CONSUMPTION_CHECK_DEEP_SLEEP	"DEEP_SLEEP CHECK"
#define INI_ITEM_CURRENT_CONSUMPTION_THR_DEEP_SLEEP		"DEEP_SLEEP THR"
#define INI_ITEM_CURRENT_CONSUMPTION_AVG_MS_DEEP_SLEEP	"DEEP_SLEEP AVG MS"

// AFE
#define INI_ITEM_AFE_USE_USER_SETTING					"USE USER AFE SETTING"
#define INI_ITEM_AFE_FREQUENCY							"FREQUENCY"
#define INI_ITEM_AFE_N_COUNT							"N COUNT"
#define INI_ITEM_AFE_U_COUNT							"U COUNT"

#define INI_ITEM_AFE_FREQUENCY_A						"FREQUENCY A"
#define INI_ITEM_AFE_N_COUNT_A							"N COUNT A"
#define INI_ITEM_AFE_U_COUNT_A							"U COUNT A"

#define INI_ITEM_AFE_FREQUENCY_B						"FREQUENCY B"
#define INI_ITEM_AFE_N_COUNT_B							"N COUNT B"
#define INI_ITEM_AFE_U_COUNT_B							"U COUNT B"

// DND
#define INI_ITEM_DND_CHECK								"CHECK DND"
#define INI_ITEM_DND_ALL_NODE_MAX_SPEC					"ALL NODE MAX SPEC"
#define INI_ITEM_DND_ALL_NODE_MIN_SPEC					"ALL NODE MIN SPEC"
#define INI_ITEM_DND_CHECK_GAP							"CHECK DND GAP"
#define INI_ITEM_DND_ALL_NODE_H_GAP_SPEC				"H GAP ALL NODE SPEC"
#define INI_ITEM_DND_ALL_NODE_V_GAP_SPEC				"V GAP ALL NODE SPEC"

// CND
#define INI_ITEM_CND_CHECK								"CHECK CND"	//add 2022.11.14 for ZTM730 CND
#define INI_ITEM_CND_ALL_NODE_MAX_SPEC					"ALL NODE MAX SPEC"
#define INI_ITEM_CND_ALL_NODE_MIN_SPEC					"ALL NODE MIN SPEC"

// HF_DND
#define INI_ITEM_HF_DND_CHECK							"CHECK HF_DND"
#define INI_ITEM_HF_DND_ALL_NODE_MAX_SPEC				"ALL NODE MAX SPEC"
#define INI_ITEM_HF_DND_ALL_NODE_MIN_SPEC				"ALL NODE MIN SPEC"
#define INI_ITEM_HF_DND_CHECK_GAP						"CHECK HF_DND GAP"
#define INI_ITEM_HF_DND_ALL_NODE_H_GAP_SPEC				"H GAP ALL NODE SPEC"
#define INI_ITEM_HF_DND_ALL_NODE_V_GAP_SPEC				"V GAP ALL NODE SPEC"

// HIGH VOLTAGE
#define INI_ITEM_HIGH_VOLTAGE_CHECK						"CHECK HIGH VOLTAGE"
#define INI_ITEM_HIGH_VOLTAGE_MAX_SPEC					"HIGH VOLTAGE MAX SPEC"
#define INI_ITEM_HIGH_VOLTAGE_MIN_SPEC					"HIGH VOLTAGE MIN SPEC"


//ONLY SELF DND
#define INI_ITEM_ONLYSELF_DND_CHECK						"CHECK ONLY SELF DND"
#define INI_ITEM_ONLYSELF_TX_ALL_NODE_MAX_SPEC			"ONLY SELF TX ALL NODE MAX SPEC"
#define INI_ITEM_ONLYSELF_TX_ALL_NODE_MIN_SPEC			"ONLY SELF TX ALL NODE MIN SPEC"
#define INI_ITEM_ONLYSELF_RX_ALL_NODE_MAX_SPEC			"ONLY SELF RX ALL NODE MAX SPEC"
#define INI_ITEM_ONLYSELF_RX_ALL_NODE_MIN_SPEC			"ONLY SELF RX ALL NODE MIN SPEC"

// SELF
#define INI_ITEM_SELF_TX_ALL_NODE_MAX_SPEC				"TX ALL NODE MAX SPEC"
#define INI_ITEM_SELF_TX_ALL_NODE_MIN_SPEC				"TX ALL NODE MIN SPEC"

#define INI_ITEM_SELF_RX_ALL_NODE_MAX_SPEC				"RX ALL NODE MAX SPEC"
#define INI_ITEM_SELF_RX_ALL_NODE_MIN_SPEC				"RX ALL NODE MIN SPEC"

// SELF_DND
#define INI_ITEM_SELF_DND_CHECK							"CHECK SELF_DND"
#define INI_ITEM_SFR_DATA_CHECK							"CHECK SFRA DATA"
#define INI_ITEM_SELF_DND_CHECK_GAP						"CHECK SELF_DND GAP"
#define INI_ITEM_SELF_DND_TX_ALL_NODE_H_GAP_SPEC		"TX H GAP ALL NODE SPEC"
#define INI_ITEM_SELF_DND_RX_ALL_NODE_H_GAP_SPEC		"RX H GAP ALL NODE SPEC"

// SELF_SATURATION
#define INI_ITEM_SELF_SATURATION_CHECK					"CHECK SELF_SATURATION"

// TRX_SHORT
#define INI_ITEM_TRX_SHORT_CHECK						"CHECK TRX SHORT"

// MEASURE_DELTA
#define INI_ITEM_MEASURE_DELTA_CHECK						"CHECK MEASURE DELTA"
#define INI_ITEM_MEASURE_DELTA_CHECK_AUTO_START				"CHECK AUTO START"
#define INI_ITEM_MEASURE_DELTA_AUTO_START_THRESHOLD			"AUTO START THRESHOLD"
#define INI_ITEM_MEASURE_DELTA_FRAME_COUNT					"FRAME COUNT"
#define INI_ITEM_MEASURE_DELTA_ALL_NODE_MAX_SPEC			"ALL NODE MAX SPEC"
#define INI_ITEM_MEASURE_DELTA_ALL_NODE_MIN_SPEC			"ALL NODE MIN SPEC"
#define INI_ITEM_MEASURE_DELTA_ALL_NODE_SELF_RX_MAX_SPEC	"ALL NODE SELF RX MAX SPEC"
#define INI_ITEM_MEASURE_DELTA_ALL_NODE_SELF_RX_MIN_SPEC	"ALL NODE SELF RX MIN SPEC"
#define INI_ITEM_MEASURE_DELTA_ALL_NODE_SELF_TX_MAX_SPEC	"ALL NODE SELF TX MAX SPEC"
#define INI_ITEM_MEASURE_DELTA_ALL_NODE_SELF_TX_MIN_SPEC	"ALL NODE SELF TX MIN SPEC"

// HW_CALIBRATION
#define INI_ITEM_HW_CALIBRATION_CHECK					"CHECK HW CALIBRATION"
#define INI_ITEM_HW_CALIBRATION_SPEC					"HW CALIBRATION SPEC"

// JITTER
#define INI_ITEM_JITTER_CHECK							"CHECK JITTER"
#define INI_ITEM_JITTER_DATA_MAX						"JITTER DATA MAX"

#define INI_ITEM_JITTER_CHECK_BY_MPZTD					"CHECK JITTER BY MPZTD"
#define INI_ITEM_JITTER_READ_FRAME_COUNT				"JITTER READ COUNT"

// DIGITAL WHEEL
#define INI_ITEM_DIGITAL_WHEEL_CHECK					"CHECK DIGITAL WHEEL"

// BUTTON
#define INI_ITEM_GPIO_BUTTON_CHECK						"CHECK GPIO BUTTON"

#define INI_ITEM_TOUCH_BUTTON_CHECK						"CHECK TOUCH BUTTON"
#define INI_ITEM_TOUCH_BUTTON_TH						"TOUCH BUTTON THRESHOLD"

// ADDITIONAL ITEM
#define INI_ITEM_ADD_TEST_POWER_OFF_WHEN_USB_DETECT		"USE POWER OFF WHEN USB DETECT"
#define INI_ITEM_ADD_TEST_POWER_CTRL_DELAY_TIME			"POWER CTRL DELAY TIME"
#define INI_ITEM_ADD_TEST_START_ALL_TEST_BY_START_PIN	"CHECK START ALL TEST BY START PIN"
#define INI_ITEM_ADD_TEST_SOLUTION_RESULT_NOFITY		"SOLUTION RESULT NOTIFY"

#define INI_ITEM_ADD_TEST_CHECK_VIRTUAL_DRAW_TEST		"CHECK VIRTUAL DRAW TEST"

// NOISE
#define INI_ITEM_CHECK_NOISE							"CHECK NOISE"
#define INI_ITEM_CHECK_NOISE_THRESHOLD					"NOISE THRESHOLD"
#define INI_ITEM_CHECK_NOISE_INTERVAL					"INTERVAL"
#define INI_ITEM_CHECK_NOISE_USEUSERAFE					"USE USER AFE"
#define INI_ITEM_CHECK_NOISE_READTIMES					"READ TIMES"
#define INI_ITEM_CHECK_NOISE_READTIMES_SCALER_COEF		"READ TIMES SCALER COEF"

#define INI_ITEM_CHECK_NOISE_FREQUENCY					"FREQUENCE"
#define INI_ITEM_CHECK_NOISE_FREQUENCY1					"FREQUENCE1"
#define INI_ITEM_CHECK_NOISE_FREQUENCY2					"FREQUENCE2"
#define INI_ITEM_CHECK_NOISE_FREQUENCY3					"FREQUENCE3"
#define INI_ITEM_CHECK_NOISE_FREQUENCY4					"FREQUENCE4"

#define INI_ITEM_CHECK_NOISE_CHECK_FREQUENCY1			"CHECK FREQUENCE1"
#define INI_ITEM_CHECK_NOISE_CHECK_FREQUENCY2			"CHECK FREQUENCE2"
#define INI_ITEM_CHECK_NOISE_CHECK_FREQUENCY3			"CHECK FREQUENCE3"
#define INI_ITEM_CHECK_NOISE_CHECK_FREQUENCY4			"CHECK FREQUENCE4"

#define INI_ITEM_CHECK_NOISE_NCOUNT						"NCOUNT"
#define INI_ITEM_CHECK_NOISE_UCOUNT						"UCOUNT"

#define INI_ITEM_PRINT_PP_VARIAITON						"Print PP Variation"

// DEV_TOOL
#define INI_ITEM_DEV_TOOL_MEASURE_LDO					"MEASURE_LDO"

#endif	// #if !defined(ZT_TEST_MODE_VIEW_INFO_INCLUDED_)

